// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IPaTD7nZw4K4Q13pMhABstNbgh0aFr0',
    appId: '1:63398519131:web:35c44fda4781bd6cf2ba7e',
    messagingSenderId: '63398519131',
    projectId: 'home-automation-502e4',
    authDomain: 'home-automation-502e4.firebaseapp.com',
    databaseURL: 'https://home-automation-502e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-502e4.appspot.com',
    measurementId: 'G-CNJK7NC73Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfv_j-fEb7rz8106CYlSzF395SEjK_I_c',
    appId: '1:63398519131:android:450096a3353ecab1f2ba7e',
    messagingSenderId: '63398519131',
    projectId: 'home-automation-502e4',
    databaseURL: 'https://home-automation-502e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-502e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApujZn3JYj6kC2HTw2EkoCNp8p2ZQ8eTg',
    appId: '1:63398519131:ios:24b0d5e4c92494c2f2ba7e',
    messagingSenderId: '63398519131',
    projectId: 'home-automation-502e4',
    databaseURL: 'https://home-automation-502e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-502e4.appspot.com',
    iosBundleId: 'com.example.homeAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApujZn3JYj6kC2HTw2EkoCNp8p2ZQ8eTg',
    appId: '1:63398519131:ios:7de2984b4d6c0cd6f2ba7e',
    messagingSenderId: '63398519131',
    projectId: 'home-automation-502e4',
    databaseURL: 'https://home-automation-502e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'home-automation-502e4.appspot.com',
    iosBundleId: 'com.example.homeAutomation.RunnerTests',
  );
}
